INSERT INTO Restaurant (Name, Website, PhoneNo, Password) VALUES ('Tim Horton''s', 'https://www.timhortons.com/ca/en/index.php', '8886011616', 'timTIM1!');
INSERT INTO Restaurant (Name, Website, PhoneNo, Password) VALUES ('Main Cafeteria', 'https://www.aramark.ca/services/food-services', '9376604708', 'abcABC1!');
INSERT INTO Restaurant (Name, Website, PhoneNo, Password) VALUES ('Epic Burger', 'https://epicburger.com', '3122433605', 'epicEPIC1!');
INSERT INTO Restaurant (Name, Website, PhoneNo, Password) VALUES ('Pizza Pizza', 'https://www.pizzapizza.ca', '4169671010', 'pizzaPIZZA1!');
INSERT INTO Restaurant (Name, Website, PhoneNo, Password) VALUES ('Subway', 'https://www.subway.com', '8008884848', 'subSUB1!');
INSERT INTO Restaurant (Name, Website, PhoneNo, Password) VALUES ('Smoke''s Poutinerie', 'smokespoutinerie.com', '9054279944', 'gravyGRAVY1!');
INSERT INTO Menu_Items (Name, RestaurantName, Price, InStock, Visible) VALUES ('Bagel B.E.L.T.', 'Tim Horton''s', 1.49, 1, 1);
INSERT INTO Menu_Items (Name, RestaurantName, Price, InStock, Visible) VALUES ('Homestyle Oatmeal', 'Tim Horton''s', 1.29, 1, 1);
INSERT INTO Menu_Items (Name, RestaurantName, Price, InStock, Visible) VALUES ('Hash Brown', 'Tim Horton''s', 1.09, 1, 1);
INSERT INTO Menu_Items (Name, RestaurantName, Price, InStock, Visible) VALUES ('Chicken Caesar Sandwich Wrap', 'Tim Horton''s', 1.69, 1, 1);
INSERT INTO Menu_Items (Name, RestaurantName, Price, InStock, Visible) VALUES ('Hearty Potato Bacon Soup', 'Tim Horton''s', 1.89, 1, 1);
INSERT INTO Menu_Items (Name, RestaurantName, Price, InStock, Visible) VALUES ('Chili', 'Tim Horton''s', 1.69, 1, 1);
INSERT INTO Menu_Items (Name, RestaurantName, Price, InStock, Visible) VALUES ('carrot muffin','Main Cafeteria', 2.60, 1, 1);
INSERT INTO Menu_Items (Name, RestaurantName, Price, InStock, Visible) VALUES ('Canadian','Pizza Pizza', 3.70, 1, 1);
INSERT INTO Menu_Items (Name, RestaurantName, Price, InStock, Visible) VALUES ('Hawaiian','Pizza Pizza', 3.90, 1, 1);
INSERT INTO Menu_Items (Name, RestaurantName, Price, InStock, Visible) VALUES ('Meatball Sub','Subway', 4.30, 1, 1);
INSERT INTO Menu_Items (Name, RestaurantName, Price, InStock, Visible) VALUES ('Classic Poutine','Smoke''s Poutinerie', 4.30, 1, 1);
INSERT INTO Menu_Items (Name, RestaurantName, Price, InStock, Visible) VALUES ('Epic Fries','Epic Burger', 2.70, 1, 1);